### ISSUE TITLE
A `SingleTickerProviderStateMixin` can only be used as a `TickerProvider` once.

### ISSUE THREAD

**Issue by IceTeaManiac** [Predidit/canvas_danmaku#1]
在 example 目录下使用 `flutter run` 运行示例代码时报错：

![Screenshot from 2024-06-04 12-03-50](https://github.com/Predidit/canvas_danmaku/assets/170739078/6eb4783c-f37b-49b6-82bc-247bc4517495)

按照报错信息将 [这一行](https://github.com/Predidit/canvas_danmaku/blob/d48381a6ec7b5c12687d2164465de49cb1510143/lib/danmaku_screen.dart#L27) 代码的 `SingleTickerProviderStateMixin` 替换成 `TickerProviderStateMixin` 看起来能解决问题。

`_DanmakuScreenState` 中同时包含了两个 `AnimationController`，即 [line32](https://github.com/Predidit/canvas_danmaku/blob/d48381a6ec7b5c12687d2164465de49cb1510143/lib/danmaku_screen.dart#L32) 和 [line35](https://github.com/Predidit/canvas_danmaku/blob/d48381a6ec7b5c12687d2164465de49cb1510143/lib/danmaku_screen.dart#L35)。他们都使用了 this 作为 `vsync` 参数的入参，而 `SingleTickerProviderStateMixin` 貌似不支持同一个 state 中包含多个 `AnimationController`。看起来报错是这个原因导致的

**Comment by Predidit** [comment]
感谢你的报告，我已经成功复现。

看上去这是我将弹幕改为分层绘制时引入的问题。

因为我在测试时为了精准的性能结果一直在使用 `profile mode` 而非 `debug mode`，故此问题一直没被发现。

方便的话可以提交一个PR吗，如果没有时间的话，我会在今天稍晚时间提交更改。

感谢你让这个库变得更好。
