### ISSUE TITLE
关于trackCount的计算

### ISSUE THREAD

**Issue by guozhigq** [Predidit/canvas_danmaku#12]
看代码中的逻辑是对计算结果 **-1** 来给字幕留空间。这样可能会导致**area**非1.0时，弹幕实际渲染会比期望的少一行吧。
另外，外部字幕的高度是未知的，所以这里的 **-1** 可能不是很通用。
```
/// 为字幕留出余量
_trackCount =  (constraints.maxHeight * _option.area / _danmakuHeight).floor() - 1;
```

**Comment by Predidit** [comment]
这确实是一个问题，我还没想好怎么调整。

也许只在 area = 1.0 时 -1 会是一个好主意？

**Comment by guozhigq** [comment]
> 这确实是一个问题，我还没想好怎么调整。
> 
> 也许只在 area = 1.0 时 -1 会是一个好主意？

我也是这么想的。
关于字幕余量/安全区域的设置暴露给调用方是不是更合适，类似于safeArea。或者干脆不用管？🤔

**Comment by Predidit** [comment]
我会在明天更新这个包

只在 area = 1.0 时 -1 

并提供一个 safeArea 选项来启用上述调整

**Comment by Predidit** [comment]
0.2.4 已经发布
