### ISSUE TITLE
全屏切换 不会显示弹幕，半屏会显示，应该是出现了两个controller 去控制

### ISSUE THREAD

**Issue by liuchuancong** [Predidit/canvas_danmaku#14]

**Comment by Predidit** [comment]
我有些没有明白这个 Issue 描述的问题

现在的行为是什么，预期的行为是什么

有截图或复现代码就更好了

**Comment by liuchuancong** [comment]
![image](https://github.com/user-attachments/assets/4ec534cd-fcf8-491b-8c32-4fb90792f8df)
![image](https://github.com/user-attachments/assets/9fad7e5c-82ec-40ab-a33e-c14aab7f12e1)
![image](https://github.com/user-attachments/assets/3498ba0e-47f5-40e0-afd0-530bdface876)
三种屏幕模式 只有第一种显示弹幕 切换的话其他两种都不会显示弹幕 
打印的controller的哈希值不一样

**Comment by Predidit** [comment]
使用 example 可以复现问题吗，如果不能的话，有没有复现问题的最小示例代码

我猜测一下可能的两种情况

1. 重复创建了控制器

热更新弹幕配置只应该通过 updateOption 方法执行

2. 视频组件全屏实现的问题

按照 flutter 的最佳实践，全屏可以通过 Hero 和路由切换优雅地进行，很多视频播放器组件内部也是那么做的

但这样对弹幕这样的场景不友好，因为这样的话实际打开了一个新页面，除了视频播放器本身之前的其他组件都不会出现在新页面上

**Comment by liuchuancong** [comment]
我进入新的屏幕 生成了新的controller,但是我退回旧的，还是用的新的 所以应该是controller的问题，example 只是单页面

**Comment by Predidit** [comment]
这似乎不是这个库的问题

控制器的生命周期应该由调用这个库的开发者维护

**Comment by liuchuancong** [comment]
所以可能需要对应一个堆栈的controller 去解决这个问题

**Comment by liuchuancong** [comment]
嗯

**Comment by fxpayback** [comment]
> 嗯

我也遇到一模一样的问题 最后这么解决的呀？

**Comment by liuchuancong** [comment]
@Predidit 沿用之前的版本是否有时间修改下

https://github.com/liuchuancong/pure_live/blob/master/lib/pkg/canvas_danmaku/danmaku_controller.dart

参考我的代码
```
danmakuController = DanmakuController(
      onAddDanmaku: (item) {},
      onUpdateOption: (option) {},
      onPause: () {},
      onResume: () {},
      onClear: () {},
    );
```
即可再次设置controller 无需关系页面

以及 Utils 添加drawMixedContent 以支持表情渲染功能

@fxpayback 可以直接搬我的代码使用
