### ISSUE TITLE
pubspec.yaml 中的 environment sdk 的最小版本约束能否降低到 3.3.4 或者更低（比如 3.0.0）？

### ISSUE THREAD

**Issue by IceTeaManiac** [Predidit/canvas_danmaku#3]
如果没有使用最新版本 Dart 的特性的话，那么降低 Dart SDK 的最小版本约束应该不会影响使用，同时可以让更多的使用者依赖这个包。

我在我的 [oneAnime fork](https://github.com/IceTeaManiac/oneAnime) 中尝试回滚到了老的 flutter 版本，该版本的 Dart SDK Version 为 3.3.4。回滚之后发现 canvas_danmaku 要求的 Dart SDK 的最小版本为 3.4.1，导致无法安装。

我的解决办法是在我的 [canvas_danmaku fork](https://github.com/IceTeaManiac/canvas_danmaku) 中修改最小版本约束为 3.3.4，再让我的 [oneAnime fork](https://github.com/IceTeaManiac/oneAnime) 直接依赖我的 [canvas_danmaku fork](https://github.com/IceTeaManiac/canvas_danmaku)，目前使用下来没遇到什么问题。

请问上游仓库能降低一下这个最小版本限制吗？

**Comment by Predidit** [comment]
`canvas_danmaku` 没有用到最新的特性，理论上应该可以直接降低依赖到 2.1.0 版本。

那个版本开始了强制空安全，更早的应该就不行了。

方便的话，可以像之前，提交一个PR。

**Comment by Predidit** [comment]
我搞错了，支持空安全的初始版本应该是 2.12

**Comment by IceTeaManiac** [comment]
不敢降太多，姑且先提个 PR 降到 3.0.0
