### ISSUE TITLE
静态弹幕不会消失

### ISSUE THREAD

**Issue by SX-Code** [Predidit/canvas_danmaku#8]
静态弹幕在没有其他滚动弹幕的情况下不回消失？

**Comment by Predidit** [comment]
目前是这样的。

有新弹幕时才会检查之前的弹幕是否过期。

弹幕一般不会太少，所有似乎也没什么问题？

**Comment by Clushdada** [comment]
> 目前是这样的。
> 
> 有新弹幕时才会检查之前的弹幕是否过期。
> 
> 弹幕一般不会太少，所有似乎也没什么问题？

静态弹幕直指顶部弹幕和底部弹幕么？这种经常遇见不消失的情况，如果当最后一条滚动弹幕消失，静态弹幕还没有过期，那么他就会一直显示在这里 @Predidit

**Comment by Predidit** [comment]
是的，我想到这么解决了，会更新在下个版本中。

**Comment by Clushdada** [comment]
> 是的，我想到这么解决了，会更新在下个版本中。

期待你尽快更新

**Comment by Predidit** [comment]
在 0.2.2 修复
