### ISSUE TITLE
进行弹幕速度设置时，弹幕会回退到初始位置

### ISSUE THREAD

**Issue by Clushdada** [Predidit/canvas_danmaku#9]
使用下面代码可通过demo复现
   TextButton(
                child:  Text('加速'),
                onPressed: () {
                  _controller.updateOption(
                      _controller.option.copyWith(duration: 5));
                },
              ),
              TextButton(
                child:  Text('恢复'),
                onPressed: () {
                  _controller.updateOption(
                      _controller.option.copyWith(duration: 8));
                },
              ),

点击加速后再点击恢复，弹幕会回到原始位置

**Comment by Clushdada** [comment]
@Predidit

**Comment by Predidit** [comment]
这和弹幕位置的计算方式相关，我想想怎么解决

**Comment by Predidit** [comment]
在 0.2.1 修复
